### ISSUE TITLE
test changetip

### ISSUE THREAD

**Issue by disanji** [bitpay/opencart-plugin#27]
Thank you, @moxing. Here's $0.01 @ChangeTip

**Comment by disanji** [comment]
Thank you, @moxing. Here's $0.01 @ChangeTip

**Comment by changetip** [comment]
Hi @moxing, @disanji sent you a Bitcoin tip worth 50 bits ($0.01), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/352604)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by disanji** [comment]
Thank you, @moxing. Here's 1bitcoin @ChangeTip

**Comment by changetip** [comment]
Hi @moxing, @disanji sent you a Bitcoin tip worth 1 1bitcoin, and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/352606)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
