### ISSUE TITLE
BitPay OpenCart 2.X not works

### ISSUE THREAD

**Issue by nicatmanaf** [bitpay/opencart-plugin#28]
BitPay OpenCart 2.X not works.. When it can be fixed. We need it is very much

**Comment by sambohler** [comment]
Hi @nicatmanaf , we are nearing completion on the development for our plugin to be compatible with OpenCart 2.X.  We'll update everyone very soon on the older issue (#19) about this.

**Comment by nicatmanaf** [comment]
Hi @sambohler . Can u say me approx date :) ? Cause we want to open our e-commerce waiting for just BitPay fix..

**Comment by sambohler** [comment]
@nicatmanaf , we are trying to ship it this coming week.

**Comment by nicatmanaf** [comment]
@sambohler  is there Beta version i can test it

**Comment by sambohler** [comment]
@nicatmanaf not quite yet, but I'll message you here as soon as we do

**Comment by ionux** [comment]
Howdy @nicatmanaf - the new OpenCart plugin has been merged and @sambohler is creating the new release package.  Just wanted to give you a head's up that it's ready for ya!
