### ISSUE TITLE
Using V2.0. Installed fine and am getting this error

### ISSUE THREAD

**Issue by forcoinsllc** [bitpay/opencart-plugin#31]
Parse error: syntax error, unexpected '[' in /CHANGEDFORPRIVACY/admin/controller/payment/bitpay.php on line 179

Whenever I try to open "edit" screen for the bitpay payment plugin I get an error. Any idea where I can start troubleshooting this?

**Comment by sambohler** [comment]
The code in question:
```php
$network_title = 'Customnet(' . $this->setting('network')['url'] . ')';
```

This line is array dereferencing the result of a function.  Simply put, $this->setting('network') returns an array, and we are immediately accessing the `url` key value via ['url'].

[Array dereferencing was a feature added in PHP 5.4](http://php.net/manual/en/language.types.array.php#example-102), which is a prerequisite for this plugin and the [PHP BitPay Client](https://github.com/bitpay/php-bitpay-client) it uses.  If you are receiving this error, you are probably using an unsupported version of PHP (< 5.4).
