### ISSUE TITLE
Latest Softalacious OC 2.0.2.0 Errors

### ISSUE THREAD

**Issue by tecan** [bitpay/opencart-plugin#32]
$network_title = 'Customnet(' . $this->setting('network')['url'] . ')';

this line gives Parse error: syntax error, unexpected '[', expecting ')' in various places in the source file. opencart 2.0.2.0 using ssl

**Comment by sambohler** [comment]
https://github.com/bitpay/opencart-plugin/issues/31#issuecomment-94746249
