### ISSUE TITLE
Parse error: syntax error, unexpected '[' in .../admin/controller/payment/bitpay.php on line 179

### ISSUE THREAD

**Issue by hoanganh2020** [bitpay/opencart-plugin#34]
Hi,

I setup on Opencart V1.5.6.4.

Error: Parse error: syntax error, unexpected '[' in .../admin/controller/payment/bitpay.php on line 179

**Comment by hoanganh2020** [comment]
$network_title = 'Customnet(' . $this->setting('network')['url'] . ')';

**Comment by ionux** [comment]
http://php.net/manual/en/language.types.array.php
As of PHP 5.4 it is possible to array dereference the result of a function or method call directly. Before it was only possible using a temporary variable.

**Comment by hoanganh2020** [comment]
My PHP version 5.2.17
