### ISSUE TITLE
Opencart 2.1.0.2

### ISSUE THREAD

**Issue by iamankits** [bitpay/opencart-plugin#42]
After installing when I go to the edit button, where I will be entering the bitpay details I get the following error :

Fatal error: Call to undefined method Loader::library() in /home/mydomain.com/public_html/admin/controller/payment/bitpay.php on line 25

```
    $this->load->library('bitpay');
```

**Comment by kleetus** [comment]
I think this is associated with #43

**Comment by pieterpoorthuis** [comment]
Fixed in release v2.2
