### ISSUE TITLE
Missing Enable Extension in OpenCart 2.2.0.0

### ISSUE THREAD

**Issue by wmpedersen** [bitpay/opencart-plugin#43]
Unsure if this is because of a new directory structure with 2.2.0.0, but after installing the 2.0 release I notice that there is no model for bitpay added under /admin/model/payment which makes me unable to enable the extension.

**Comment by kleetus** [comment]
I (also) found that the latest version of OpenCart >2.1 does NOT work with our latest version of BitPay plugin for the same. OpenCart changed the way they register/load extensions into their platform and we have not changed over to the new style. 

If and when we update this plugin for this change, I will reach out to you.

**Comment by pieterpoorthuis** [comment]
Fixed in release v2.2
