### ISSUE TITLE
Opencart 2.3.0.2

### ISSUE THREAD

**Issue by spletnib** [bitpay/opencart-plugin#45]
I cannot install extension. I receive error: Fatal error: Class 'bitpay' not found in /home/mypage/public_html/mypage/system/engine/loader.php on line 110

**Comment by easye35** [comment]
I have same problem
Fatal error: Class 'bitpay' not found in /home/ourbchkk/haleysboutique/system/storage/modification/system/engine/loader.php on line 110

**Comment by ajp8164** [comment]
Doesn't work with Opencart 2.3.x

**Comment by pieterpoorthuis** [comment]
Fixed in release v2.2
