### ISSUE TITLE
Opencart 2.3.0.2 error - currently unable to handle this request. HTTP ERROR 500 

### ISSUE THREAD

**Issue by ossovik** [bitpay/opencart-plugin#46]
Hello
After I got help to install a new theme Menda Responsive, now when I try to edit a product or category, and when i try to save it, I get this error:
domain.com currently unable to handle this request. HTTP ERROR 500

Any idea how to solve this?

Thanks

Olav

**Comment by pieterpoorthuis** [comment]
Fixed in release v2.2
