### ISSUE TITLE
Parse Error - Unexpected ')' on line 179.

### ISSUE THREAD

**Issue by ukulture** [bitpay/opencart-plugin#47]
I am on 2.0.2 and have tried both the 2.0.1 and the 2.1 and neither are working, it installs through extension installer with no issue. But when I go to payments and click the 'Install '+' button I am getting the following error page - Parse error - unexpected ')' on line 179 catalog\controller\payment. This is line 179. Any idea on what can be causing this error?

$network_title = 'Customnet(' . $this->setting('network')['url'] . ')';

Thanks Jay

**Comment by pieterpoorthuis** [comment]
Probably the problem with OpenCart installer or incompatibility with this particular old version. Unable to reproduce on supported OpenCart versions.
