### ISSUE TITLE
API key keeps disconnecting

### ISSUE THREAD

**Issue by ajp8164** [bitpay/opencart-plugin#48]
I know this issue is a bit specific but hopefully someone can help me out. I am using your opencart plugin for your store, however over the last 6 months or so I notice that my connection seems to become invalid and the API keys drop about once a week. This causes the plugin to stop and not be able to connect to the API server rendering it useless. I have checked the logs of the plugin and I am only getting messages about the service not being enabled once its offline and customers go through the checkout. It’s gotten so bad I’ve needed to setup coinpayments as an alternative just so I don’t lose sales.

**Comment by pieterpoorthuis** [comment]
Need more information in order to fix
