### ISSUE TITLE
Support for OpenCart v3

### ISSUE THREAD

**Issue by pieterpoorthuis** [bitpay/opencart-plugin#52]
OpenCart v3 was released in June 2017

Current plugin does not work with OpenCart v3. Putting v3 support on the roadmap.

**Comment by bluebrad** [comment]
any update?

**Comment by bluebrad** [comment]
still looking for an update

**Comment by pieterpoorthuis** [comment]
OpenCart v3 support is now available at https://github.com/bitpay/opencart3-plugin/releases
