### ISSUE TITLE
Not redirect to payment page 

### ISSUE THREAD

**Issue by madhavkumar60** [bitpay/opencart-plugin#54]
Not redirect to payment page while checkout. please resolve it asap.

**Comment by madhavkumar60** [comment]
Its working properly in test mode.

**Comment by pieterpoorthuis** [comment]
Can you provide logs & screenshots?

On production the minimum order value is USD 5.
Also make sure your BitPay production merchant account is fully verified for doing payments.

**Comment by madhavkumar60** [comment]
Hi pieterpoorthuis,
Thanks for your response.
Now its working fine.
